podcasts/urls.py
from django.conf.urls import patterns, url

from . import feeds
from . import views


urlpatterns = patterns(
    'django.views.generic.date_based',
    url(r'^$',
        views.ArchiveIndexView.as_view(), name='news_archive_index'),
    url(r'^search$',
        views.search, name='buscador_podcast'),
    url(r'^mas$',
        views.mas, name='mas_podcast'),
    url(r'^(?P<year>\d{4})/$',
        views.YearArchiveView.as_view(), name='news_archive_year'),

    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/$',
        views.MonthArchiveView.as_view(), name='news_archive_month'),

    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/$',
        views.DayArchiveView.as_view(), name='news_archive_day'),

    url((r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/'
         r'(?P<slug>[-\w]+)/$'),
        views.DetailView.as_view(), name='news_detail'),

    url(r'^feed/$', feeds.NewsFeed())
)

prj/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls import *  # NOQA
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

#admin.autodiscover()

urlpatterns = [ #i18n_patterns('',
    url(r'^admin/', include(admin.site.urls)),  # NOQA
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap',
        {'sitemaps': {'cmspages': CMSSitemap}}),
    url(r'^select2/', include('django_select2.urls')),
    url(r'^podcasts/', include('podcasts.urls')),
    url(r'^noticias/', include('noticias.urls')),

    url(r'^', include('cms.urls')),
    url(r'^', include('djangocms_forms.urls')),
    url(r'^programas/', include('programas.urls', namespace="programas")),
]

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns = patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',  # NOQA
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        ) + staticfiles_urlpatterns() + urlpatterns  # NOQA

programas/urls.py
from django.conf.urls import patterns, url
from . import views

urlpatterns = [
    url(r'^progactual$', views.actual, name='actual'),
    url(r'^$', views.IndexView.as_view()),
]

prj/templates/base.html
<!doctype html>
{% load cms_tags staticfiles sekizai_tags menu_tags %}
{% load url from future %}
<html>
    <head>
        <meta charset="utf-8">
        <title>{% block title %}This is my new project home page{% endblock title %}</title>
        <meta name="viewport" content="width=device-width">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.4/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.4/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

        {% render_block "css" %}
        <link href="{{STATIC_URL}}styles.css" rel="stylesheet" type="text/css"/>
    </head>

    <body>
        <div id="modal-noticias" class="modal fade" role="dialog" tabindex="-1"></div>
        <div id="modal-campanas" class="modal fade" role="dialog" tabindex="-1"></div>

        {% cms_toolbar %}
        <!--div class="container"-->
            <!--div class="navbar navbar-default" role="navigation">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">Project name</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        {% show_menu 0 1 100 100 "menu.html" %}
                    </ul>
                </div>
            </div-->
        {% block content %}{% endblock content %}


        {% render_block "js" %}
        <!--script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script-->
        <!--script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.4/js/bootstrap.min.js"></script-->
        <!--script src="{{STATIC_URL}}jquery.cookie.js"></script-->
        <script type="text/javascript" >
            jQuery.noConflict();
            (function( $ ) {
                $(function() {

                    $('#modal-campanas').on('hidden.bs.modal', function () {
                        $(this).empty();
                    });

                    $('ul.section-menu').children().first().addClass('active');
                    $("nav a").click(function(evn){
                        evn.preventDefault();
                        $('html,body').animate({
                                scrollTop: $(this.hash).offset().top
                            }, 500);

                        $('ul.section-menu > li.active').removeClass('active');

                        $(this).parent().addClass('active');
                        $(this).blur();

                    });
                    $(document).scroll(function() {
                        var li = $('nav a[href="#'+$('section:hover').attr('id')+'"]').parent();
                        if (li.is('li') ){
                            $('nav li.active').removeClass('active');
                            li.addClass('active');
                        }
                    });

                    $(document).on("click", ".modal-noticias-link", function () {
                        $("#modal-noticias").empty();
                        var modalid = $(this).data('id');
                        var modal = $('#noticia'+modalid);
                        $("#modal-noticias").append( modal.clone()[0] );
                    });
                    $(document).on("click", ".modal-campanas-link", function () {
                        $("#modal-campanas").empty();
                        var modalid = $(this).data('id');
                        var modal = $('#campana'+modalid);
                        $("#modal-campanas").append( modal.clone()[0] );
                        var url= $(this).data('src');
                        var ifr= '<iframe src="'+url+'" width="550" height="400" frameBorder="0"></iframe>';
                        $("#modal-campanas .modal-body").append(ifr);
                    });

                    $(document).ready(function (){
                        $(".owl-prev").empty();
                        $(".owl-next").empty();
                        $(".owl-prev").append("<i class='fa fa-chevron-left fa-2x'></i>");
                        $(".owl-next").append("<i class='fa fa-chevron-right fa-2x'></i>");

                        $.ajax({
                            url : "{% url 'programas:actual' %}", // the endpoint
                            type : "GET", // http method
                            //data : { }, // data sent with the post request

                            // handle a successful response
                            success : function(json) {
                                $('#prog-actual').append(json['programa']); // remove the value from the input
                            },

                            // handle a non-successful response
                            error : function(xhr,errmsg,err) {
                                $('#results').html("<div class='alert-box alert radius' data-alert>Oops! We have encountered an error: "+errmsg+
                                    " <a href='#' class='close'>&times;</a></div>"); // add the error to the dom
                                console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
                            }
                        });

                        //$('section').each(function(){this.style['min-height']=window.innerHeight+'px';})
                        $('.search-form').on('submit', function(e){
                            e.preventDefault();
                            buscar_podcasts();
                        });

                    });

                    $(document).on("click", "#mostrar-noticias", function () {mas_noticias();} );
                    $(document).on("click", "#borrar-noticias", function () {borrar_noticias();} );
                    $('#borrar-noticias').hide();
                    function mas_noticias(pagina){
                        //key = "'"+$('#mas-noticias').val() +"'";
                        //token = "csrfmiddlewaretoken : '{{ csrf_token }}'"; //" + $(".search-form input[name='csrfmiddlewaretoken']").val()+"'";

                        $.ajax({
                          url : "{% url 'todas_noticias' %}", // the endpoint
                          type : "GET", // http method
                          dataType: "html",
                          data: {'page': pagina},

                          // handle a successful response
                          success : function(data) {
                              $('#lista-noticias').empty();
                              $('#lista-noticias').append(data); // agrego html al bloque
                              $('#borrar-noticias').show();
                              $('#mostrar-noticias').hide();
                              $(document).off("click", "#mostrar-noticias" );
                              $(document).on("click", "#mostrar-noticias", function () {mostrar_noticias();} );

                          },

                          // handle a non-successful response
                          error : function(xhr,errmsg,err) {
                              $('#results').html("<div class='alert-box alert radius' data-alert>Oops! We have encountered an error: "+errmsg+
                                  " <a href='#' class='close'>&times;</a></div>"); // add the error to the dom
                              console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
                          }
                        });
                    };
                    function borrar_noticias(){
                        $('#lista-noticias').hide();
                        $('#borrar-noticias').hide();
                        $('#mostrar-noticias').show();
                    };
                    function mostrar_noticias(){
                        $('#lista-noticias').show();
                        $('#borrar-noticias').show();
                        $('#mostrar-noticias').hide();
                    };

                });
            })(jQuery);

            function buscar_podcasts(){
                key = "'"+$('#podcast_search_data').val() +"'";
                //token = "csrfmiddlewaretoken : '{{ csrf_token }}'"; //" + $(".search-form input[name='csrfmiddlewaretoken']").val()+"'";
                $.ajax({
                  url : "{% url 'buscador_podcast' %}", // the endpoint
                  type : "GET", // http method
                  dataType: "html",
                  data : { clave : key }, // data sent with the post request
                  // handle a successful response
                  success : function(data) {
                      $('#podcasts_latest').hide();
                      $('.busqueda_podcasts').remove();
                      $('.podcasts .content').append(data); // agrego html al bloque
                  },

                  // handle a non-successful response
                  error : function(xhr,errmsg,err) {
                      $('#results').html("<div class='alert-box alert radius' data-alert>Oops! We have encountered an error: "+errmsg+
                          " <a href='#' class='close'>&times;</a></div>"); // add the error to the dom
                      console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
                  }
                });
            };
            function mas_podcasts(pagina){
                key = "'"+$('#podcast_search_data').val() +"'";
                //token = "csrfmiddlewaretoken : '{{ csrf_token }}'"; //" + $(".search-form input[name='csrfmiddlewaretoken']").val()+"'";
                $.ajax({
                  url : "{% url 'mas_podcast' %}", // the endpoint
                  type : "GET", // http method
                  dataType: "html",
                  data : { clave : key, 'page': pagina }, // data sent with the post request
                  // handle a successful response
                  success : function(data) {
                      $('#podcasts_latest').hide();
                      $('.busqueda_podcasts .pagination').remove();
                      $('.busqueda_podcasts').append(data); // agrego html al bloque
                  },

                  // handle a non-successful response
                  error : function(xhr,errmsg,err) {
                      $('#results').html("<div class='alert-box alert radius' data-alert>Oops! We have encountered an error: "+errmsg+
                          " <a href='#' class='close'>&times;</a></div>"); // add the error to the dom
                      console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
                  }
                });
            };
            function volver_buscar(){
                $('#podcasts_latest').show();
                $('#podcast_search_data').val('');
                $('.busqueda_podcasts').remove();
            };
        </script>
    </body>
</html>

prj/templates/feature.html
{% extends "base.html" %}
{% load cms_tags %}

{% block title %}{% page_attribute "page_title" %}{% endblock title %}

{% block content %}
    <div class="jumbotron">
        {% placeholder "feature" %}
    </div>
    <div>
        {% placeholder "content" %}
    </div>
{% endblock content %}

prj/templates/menu.html
{% load i18n menu_tags cache %}

{% for child in children %}
    <li class="{% if child.ancestor %}ancestor{% endif %}
        {% if child.selected %} active{% endif %}
        {% if child.children %} dropdown{% endif %}">
        {% if child.children %}
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                {{ child.get_menu_title }} <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
                {% show_menu from_level to_level extra_inactive extra_active template "" "" child %}
            </ul>
        {% else %}
            <a href="{{ child.get_absolute_url }}"><span>{{ child.get_menu_title }}</span></a>
        {% endif %}
    </li>
    {% if class and forloop.last and not forloop.parentloop %}{% endif %}
{% endfor %}

prj/templates/page.html
{% extends "base.html" %}
{% load cms_tags %}
{% block title %}{% page_attribute "page_title" %}{% endblock title %}

{% block content %}
    {% placeholder "content" %}
{% endblock content %}